version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 0
    groups:
      bun-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 0
    groups:
      actions-security:
        applies-to: security-updates
        patterns:
          - "*"
