on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'
        extended: true

    - name: Build
      run: make

    - name: Upload Files
      run: find . -type d | xargs -I{} curl --user ${{ secrets.USERNAME }}:${{ secrets.PASSWORD }} --digest -X MKCOL ${{ secrets.URL }}/gaato.net/{} && find . -type f | xargs -I{} curl --user ${{ secrets.USERNAME }}:${{ secrets.PASSWORD }} --digest -T{} ${{ secrets.URL }}/gaato.net/{}
