name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python gaato_net/generate_secretkey_setting.py > gaato_net/local_settings.py
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        env DJANGO_SETTINGS_MODULE=gaato_net.settings_dev python manage.py test
